### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-reporting#29]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] stock_analysis - By @omejia26 - #34 
- [ ] stock_picking_partner_lang
- [ ] stock_picking_webkit
- [x] stock_valued_picking_report - By @chienandalu - #35
