### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-reporting#37]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] stock_picking_partner_lang
- [ ] stock_picking_webkit
- [x] stock_picking_report_custom_description - By @sergio-teruel - #45 
- [x] stock_valued_picking_report > stock_picking_report_valued - By @luismontalba - #44
